name: macOS-python

on: [push]

jobs:
  build-test:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7' ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: packages
      run: brew install eigen
    - name: submodule
      run: git submodule update --init --recursive
    - name: pip
      run: pip install ./
    - name: test
      run: python ./python-examples/classical-mds.py
